#!/bin/bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$DOKKU_DISTRO" in
  ubuntu)
    apt-get install -qq -y software-properties-common python-software-properties
    add-apt-repository -y "deb http://nginx.org/packages/debian/ squeeze nginx"
    apt-get update
    apt-get install -qq -y nginx dnsutils
    ;;

  opensuse)
    zypper -q in -y nginx bind-utils
    ;;
esac
